// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJk0lFuvTnxaNandhlP3bvbhB2TXlsgW4',
    appId: '1:84972958633:web:5dac7d6c7af113c976cab8',
    messagingSenderId: '84972958633',
    projectId: 'billit-62fe4',
    authDomain: 'billit-62fe4.firebaseapp.com',
    databaseURL: 'https://billit-62fe4-default-rtdb.firebaseio.com',
    storageBucket: 'billit-62fe4.firebasestorage.app',
    measurementId: 'G-JT53QNP33Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_dJaLBMDZqN_yLeEKDfdWmYhzNRHiC-w',
    appId: '1:84972958633:android:4f44614365203d2476cab8',
    messagingSenderId: '84972958633',
    projectId: 'billit-62fe4',
    databaseURL: 'https://billit-62fe4-default-rtdb.firebaseio.com',
    storageBucket: 'billit-62fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7m7mpL7Z7eHIAJg8TWJQezdeoRBJv7_Y',
    appId: '1:84972958633:ios:c13152378ef2b40d76cab8',
    messagingSenderId: '84972958633',
    projectId: 'billit-62fe4',
    databaseURL: 'https://billit-62fe4-default-rtdb.firebaseio.com',
    storageBucket: 'billit-62fe4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7m7mpL7Z7eHIAJg8TWJQezdeoRBJv7_Y',
    appId: '1:84972958633:ios:c13152378ef2b40d76cab8',
    messagingSenderId: '84972958633',
    projectId: 'billit-62fe4',
    databaseURL: 'https://billit-62fe4-default-rtdb.firebaseio.com',
    storageBucket: 'billit-62fe4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhk71_EMiPpWtDc7fSfFSHqBukgik0OII',
    appId: '1:60314180413:web:32c1964dcb1f4cab38c354',
    messagingSenderId: '60314180413',
    projectId: 'billitv1-51105',
    authDomain: 'billitv1-51105.firebaseapp.com',
    storageBucket: 'billitv1-51105.firebasestorage.app',
    measurementId: 'G-GEYKFBSVXS',
  );

}